{% set name = "seabreeze" %}
{% set version = "1.0.0rc3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/ap--/python-seabreeze.git
  git_rev: v{{ version }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  run:
    - python
    - numpy
    - libusb-compat  # [linux]
    - pyusb
    - future
    - enum34  # [py<34]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython
    - setuptools_scm
    - pkgconfig
    - pkg-config  # [not win]
    - libusb-compat  # [linux]
    - pytest-runner

test:
  requires:
    - pytest<5
  commands:
    - "pytest"
  imports:
    - seabreeze
    - seabreeze.cseabreeze
    - seabreeze.pyseabreeze

about:
  home: http://github.com/ap--/python-seabreeze
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Python module for Ocean Optics spectrometer'

extra:
  recipe-maintainers:
    - 'ap--'
