provider:
  linux: circle
  osx: travis
  win: appveyor
  linux_ppc64le: None
  linux_aarch64: None

github:
  user_or_org: ap--

travis:
  secure:
    BINSTAR_TOKEN: pqxuqI0MP1aQ4BV4nSGNYORFlbBrd61PMO/Ro9fOCJYHzO4SFPZdfk80Op/03vwHWi47LQfMRcBUUbR3UWi6zDu5WX2tdPjC8heANX4V2dQarSqpa7UjVB//LwDsYQhwllwbXhaRg0Do8NRyncm3haISj6nEVPL7vy4s77jlURTqBFptlk54c/7izAFI/DsD0fBTKCynboUW4IqHBXz4HJDbURF7/1LqSqxyEZDVMvli1JiWX3QZm7UxQBYJmhVVJoYzpWYt9N9jSnumXJKtqyAHmk70T8sSFqEQmb7XThcBnkUVO2Ct3o6kN1HWX2LKkYxBFJEpeR4HqeBY3odz8tDhyMTtSHR15oDWPoajcT7dMZ76NMw8c5yfb/JF1t6kPMya7zw2Sew39+nnv9KW/SuKnnJmHnM50aYu8CxMfggKgzCCyNzbyFK3ekCz9PoyO107ZjNGFNSVkbwydGbV8bIA64J6qi2tapzm5u5nzaBbA1x9mpz57a212EhoVzXkQ4tLOzIy4sBvaRRgjosEAdDMDJYHw1pZCII9RREWFz2PXXOvGBGHf2NVMrbnI5FdAUDQVPFlr0CyLnMt3S4FRkH/UR6CqKGOoA70AHe2oyxkWG/2IyDWhNuv1IbVA5Hr3jaUCfNiJya4pzmrAxNTq2W7oTpIQTHY7T7XjNHjIP8=
appveyor:
  secure:
    BINSTAR_TOKEN: MF14/kVR5W6wBUaj/Qm/9yEHuxa8mzFDXSbeQXpVZh9BCdlHjwQSJ4UML1s7QTgI
azure:
  enabled: false
  force: false
